### PR TITLE
handle list opts

### PR DESCRIPTION
**Pull request by mithereal**
httpoision allows a list of options for request/5, this duplicates the feature, i needed it to use as a drop in replacement for ex_maps

### CODE REVIEW

**Comment by petrohi** [comment]
@mithereal please see my comments and also please rebase.

**Comment by mithereal** [comment]
done

**Comment by petrohi** [comment]
Also please see comments regarding guards and using Map.new.

**Comment by mithereal** [comment]
sorry i dont know how to see your comments regarding guards

**Comment by petrohi** [comment]
Sorry--forgot to click submit. Please see above.

**Comment by petrohi** [comment]
Added list of options support to master--please try and I will create hex.pm release.

**Pull request closed without merging**
