### PR TITLE
Conn options fix

### PR DESCRIPTION
**Pull request by MouseRider**
Fix conn_opts code to respect options passed as parameter of request call.

### CODE REVIEW

**Comment by petrohi** [comment]
Now that I tested with this change I see one issue. `conn_opts` when passed into request are respected only when new connection is created as a result of the request. In normal conditions when connections are reused it will have no effect. So this can be very confusing for someone to debug if they are passing different options to the same connection pool.

What is your use case for this?

**Comment by MouseRider** [comment]
I thought that pool is based on the params of the request including options…
What parameters of request/ environment vars are used to identify worker pool?
Do I need to create different pool for different set of those parameters?

My current scenario is reverse proxy implementation and I’m using machine gun to forward GRPC requests.
I have the following forwarder code:

  def forward(:"HTTP/2", method, to_url, headers, req_body) do
    Log.info("HTTP/2 forwarding to URL: #{inspect to_url}")
    case MachineGun.request(
      method,
      "http://" <> to_url,
      req_body,
      headers,
      %{
        pool_timeout: @pool_timeout,
        request_timeout: @req_timeout,
        pool_group: :default,
        pool_size: @pool_size,
        conn_opts: %{
          protocols: [:http2],
          transport: :tcp,
          connect_timeout: @connect_timeout
        }
      })
    do
      {:ok, %MachineGun.Response{body: resp_body, status_code: status, headers: headers, trailers: nil} }
        -> {status, headers, resp_body, []}
      {:ok, %MachineGun.Response{body: resp_body, status_code: status, headers: headers, trailers: trailers} }
        -> {status, headers, resp_body, trailers}
      {:error, %MachineGun.Error{reason: reason}}
        -> {:error, reason}
      err
        -> {:error, inspect err}
    end
  end

I need to have HTTP/2 over TCP(not TLS) connection to backend servers (see highlighted), and I’m passing those using conn_opts.
My assumption is that pool of workers would be created for those parameters and connection will be reused when set of parameters match.

Thank you,
Alex

**Comment by MouseRider** [comment]
My bad.
Just looked at the code.

I see your point.
In my case it is exactly what I need (I do not need that flexibility)

The problem is exactly as you pointed it out but it is not related to my changes.

The simplest way to address this issue in current architecture is to change pool name generation to be based on more than just host and port…

Alex

P.S. Could you please let me know when do you plan to do a new release with these changes? Just so I can set up expectations on our project when we can remove github based dependency.

**Comment by petrohi** [comment]
I suggest you set this in your config.exs:

```
config :machine_gun,
  default: %{
    pool_size: @pool_size,
    pool_timeout:  @pool_timeout,
    request_timeout: @req_timeout,
    conn_opts: %{
        protocols: [:http2],
        transport: :tcp,
        connect_timeout: @connect_timeout
    }
}
```

With this you don't need to pass options to `MachineGun.request`.

**Comment by MouseRider** [comment]
Thank you. This would be better for sure.  😊


We are working on performance tweaks and I noticed that you do not expos poolboy’s strategy option.
Will it be ok if I’ll add it?

Thank you,
Alex

**Comment by petrohi** [comment]
Then I will revert `conn_opts` support in `MachineGun.request`.

Regarding strategy option--yes--please submit the PR.

**Comment by MouseRider** [comment]
Before you do so.
We are planning to use machine_gun as http/1.1 client as well in the same application.
Having single config would not allow me to switch between protocols versions…
Or should I use different pool group?

Thanks,
Alex

**Comment by MouseRider** [comment]
One more suggestion.
To reduce confusion with conn_ops and other options, do you think it might be better to remove opts from request call an replace it with explicit params that make sense in request (i.e. pool_group – to pick up config for the pool options, optional parameters request_timeout and pool_timeout)?  This way consumer of the library would not get confused on what can be supplied where?
We can introduce new request method and mark current one as deprecated.

Alex

**Comment by petrohi** [comment]
Currently you can specify pool_group in request opts. This will force using corresponding configuration.

```
MachineGun.request(..., %{pool_group: :group1})
```
```
config :machine_gun,
  group1: %{...}
```

**Pull request merged**
