### PR TITLE
 Added 'strategy' to pool configartion options.

### PR DESCRIPTION
**Pull request by MouseRider**
Allows configuration of poolboy pool strategy :lifo(default) or :fifo,

### CODE REVIEW

**Comment by petrohi** [comment]
Please rebase.

**Comment by MouseRider** [comment]
Done

**Comment by petrohi** [comment]
Please see my comment about `conn_opts`

**Comment by MouseRider** [comment]
Done.

**Comment by petrohi** [comment]
@MouseRider published new version with your changes:

https://hex.pm/packages/machine_gun

**Pull request merged**
